env: "dev"
db: "pgx"


http_server: 
  address: ":3008"

grpc_serv:
  port: ":50053"

grpc_client:
  address_client: "address:50057"
  cart_client: "cart:50056"
  inventory_client: "inventory:50051"
  order_client: "order:50054"