syntax = "proto3";

package proto;

option go_package = "proto/orderpb";
import "google/protobuf/empty.proto";


service OrderService{
    rpc CreateOrder(CreatOrderRequest) returns (CreatOrderResponse);
    rpc CreateOrderItem(CreateOrderItemRequest) returns (google.protobuf.Empty);
}

	
message CreatOrderRequest {
		int64 user_id=1;
		int64 address_id=2;
		string order_number=3;
		float subtotal=4;
		float shipping=5;
		float tax=6;
		float discount=7;
		float total=8;
}

message CreatOrderResponse{
     int64 order_id=1; 
     int64 order_number=2;
     float shipping=3;
     float tax=4;
     float discount=5;
     float total=6;
}


message CreateOrderItemRequest{
			int64 order_id=1;
			int64 product_id=2;
			int64 warehouse_id=3;
			int64 quantity = 4;
			float unitPrice =5;
			float total_price=6;
}