// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0--rc1
// source: proto/order.proto

package orderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AddressId     int64                  `protobuf:"varint,2,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	OrderNumber   int64                  `protobuf:"varint,3,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	Subtotal      float32                `protobuf:"fixed32,4,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	Shipping      float32                `protobuf:"fixed32,5,opt,name=shipping,proto3" json:"shipping,omitempty"`
	Tax           float32                `protobuf:"fixed32,6,opt,name=tax,proto3" json:"tax,omitempty"`
	Discount      float32                `protobuf:"fixed32,7,opt,name=discount,proto3" json:"discount,omitempty"`
	Total         float32                `protobuf:"fixed32,8,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatOrderRequest) Reset() {
	*x = CreatOrderRequest{}
	mi := &file_proto_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatOrderRequest) ProtoMessage() {}

func (x *CreatOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatOrderRequest.ProtoReflect.Descriptor instead.
func (*CreatOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreatOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatOrderRequest) GetAddressId() int64 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

func (x *CreatOrderRequest) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

func (x *CreatOrderRequest) GetSubtotal() float32 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *CreatOrderRequest) GetShipping() float32 {
	if x != nil {
		return x.Shipping
	}
	return 0
}

func (x *CreatOrderRequest) GetTax() float32 {
	if x != nil {
		return x.Tax
	}
	return 0
}

func (x *CreatOrderRequest) GetDiscount() float32 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *CreatOrderRequest) GetTotal() float32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreatOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderNumber   int64                  `protobuf:"varint,2,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	Shipping      float32                `protobuf:"fixed32,3,opt,name=shipping,proto3" json:"shipping,omitempty"`
	Tax           float32                `protobuf:"fixed32,4,opt,name=tax,proto3" json:"tax,omitempty"`
	Discount      float32                `protobuf:"fixed32,5,opt,name=discount,proto3" json:"discount,omitempty"`
	Total         float32                `protobuf:"fixed32,6,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatOrderResponse) Reset() {
	*x = CreatOrderResponse{}
	mi := &file_proto_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatOrderResponse) ProtoMessage() {}

func (x *CreatOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatOrderResponse.ProtoReflect.Descriptor instead.
func (*CreatOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreatOrderResponse) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreatOrderResponse) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

func (x *CreatOrderResponse) GetShipping() float32 {
	if x != nil {
		return x.Shipping
	}
	return 0
}

func (x *CreatOrderResponse) GetTax() float32 {
	if x != nil {
		return x.Tax
	}
	return 0
}

func (x *CreatOrderResponse) GetDiscount() float32 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *CreatOrderResponse) GetTotal() float32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateOrderItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	WarehouseId   int64                  `protobuf:"varint,3,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     float32                `protobuf:"fixed32,5,opt,name=unitPrice,proto3" json:"unitPrice,omitempty"`
	TotalPrice    float32                `protobuf:"fixed32,6,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderItemRequest) Reset() {
	*x = CreateOrderItemRequest{}
	mi := &file_proto_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderItemRequest) ProtoMessage() {}

func (x *CreateOrderItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderItemRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderItemRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateOrderItemRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateOrderItemRequest) GetWarehouseId() int64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *CreateOrderItemRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateOrderItemRequest) GetUnitPrice() float32 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *CreateOrderItemRequest) GetTotalPrice() float32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

var File_proto_order_proto protoreflect.FileDescriptor

const file_proto_order_proto_rawDesc = "" +
	"\n" +
	"\x11proto/order.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"\xea\x01\n" +
	"\x11CreatOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"address_id\x18\x02 \x01(\x03R\taddressId\x12!\n" +
	"\forder_number\x18\x03 \x01(\x03R\vorderNumber\x12\x1a\n" +
	"\bsubtotal\x18\x04 \x01(\x02R\bsubtotal\x12\x1a\n" +
	"\bshipping\x18\x05 \x01(\x02R\bshipping\x12\x10\n" +
	"\x03tax\x18\x06 \x01(\x02R\x03tax\x12\x1a\n" +
	"\bdiscount\x18\a \x01(\x02R\bdiscount\x12\x14\n" +
	"\x05total\x18\b \x01(\x02R\x05total\"\xb2\x01\n" +
	"\x12CreatOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12!\n" +
	"\forder_number\x18\x02 \x01(\x03R\vorderNumber\x12\x1a\n" +
	"\bshipping\x18\x03 \x01(\x02R\bshipping\x12\x10\n" +
	"\x03tax\x18\x04 \x01(\x02R\x03tax\x12\x1a\n" +
	"\bdiscount\x18\x05 \x01(\x02R\bdiscount\x12\x14\n" +
	"\x05total\x18\x06 \x01(\x02R\x05total\"\xd0\x01\n" +
	"\x16CreateOrderItemRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12!\n" +
	"\fwarehouse_id\x18\x03 \x01(\x03R\vwarehouseId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12\x1c\n" +
	"\tunitPrice\x18\x05 \x01(\x02R\tunitPrice\x12\x1f\n" +
	"\vtotal_price\x18\x06 \x01(\x02R\n" +
	"totalPrice2\x9c\x01\n" +
	"\fOrderService\x12B\n" +
	"\vCreateOrder\x12\x18.proto.CreatOrderRequest\x1a\x19.proto.CreatOrderResponse\x12H\n" +
	"\x0fCreateOrderItem\x12\x1d.proto.CreateOrderItemRequest\x1a\x16.google.protobuf.EmptyB\x10Z\x0e/proto/orderpbb\x06proto3"

var (
	file_proto_order_proto_rawDescOnce sync.Once
	file_proto_order_proto_rawDescData []byte
)

func file_proto_order_proto_rawDescGZIP() []byte {
	file_proto_order_proto_rawDescOnce.Do(func() {
		file_proto_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_order_proto_rawDesc), len(file_proto_order_proto_rawDesc)))
	})
	return file_proto_order_proto_rawDescData
}

var file_proto_order_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_order_proto_goTypes = []any{
	(*CreatOrderRequest)(nil),      // 0: proto.CreatOrderRequest
	(*CreatOrderResponse)(nil),     // 1: proto.CreatOrderResponse
	(*CreateOrderItemRequest)(nil), // 2: proto.CreateOrderItemRequest
	(*emptypb.Empty)(nil),          // 3: google.protobuf.Empty
}
var file_proto_order_proto_depIdxs = []int32{
	0, // 0: proto.OrderService.CreateOrder:input_type -> proto.CreatOrderRequest
	2, // 1: proto.OrderService.CreateOrderItem:input_type -> proto.CreateOrderItemRequest
	1, // 2: proto.OrderService.CreateOrder:output_type -> proto.CreatOrderResponse
	3, // 3: proto.OrderService.CreateOrderItem:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_order_proto_init() }
func file_proto_order_proto_init() {
	if File_proto_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_order_proto_rawDesc), len(file_proto_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_order_proto_goTypes,
		DependencyIndexes: file_proto_order_proto_depIdxs,
		MessageInfos:      file_proto_order_proto_msgTypes,
	}.Build()
	File_proto_order_proto = out.File
	file_proto_order_proto_goTypes = nil
	file_proto_order_proto_depIdxs = nil
}
