package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"apigateway/graph/model"
	"apigateway/proto/userpb"
	"context"
	"fmt"
	"log"
	"strconv"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*model.User, error) {
	userID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		log.Println("Error in the conver the id ",err)
		return nil, err
	}
	rsp, err := r.UserClient.GetUserById(ctx, &userpb.GetUserByIdRequest{
		Id: userID,
	})

	if err!=nil {
		log.Println("error to get the user ",err)
		return  nil, err
	}

	return &model.User{
		ID:    id,
		Name:  &rsp.Name,
		Email: &rsp.Email,
		Role:  &rsp.Role,
	}, nil
}
