package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"apigateway/graph/model"
	"context"
)

// UpdateWarehouse is the resolver for the updateWarehouse field.
func (r *mutationResolver) UpdateWarehouse(ctx context.Context, input model.NewWarehouse) (*model.Warehouse, error) {
	rsp,err:=r.UpdateWarehouse(ctx,input);
	if err!=nil {
		return nil,err
	}

	return  &model.Warehouse{
		ID: rsp.ID,
		Name: rsp.Name,
		City:rsp.City ,
		Address: rsp.Address,
		UpdatedAt: rsp.UpdatedAt,
		CreatedAt: rsp.CreatedAt,
	},nil
}

// DeleteWarehouse is the resolver for the deleteWarehouse field.
func (r *mutationResolver) DeleteWarehouse(ctx context.Context, id string) (string, error) {
	id,err:=r.DeleteWarehouse(ctx,id)
	if err!=nil {
		return " ",err
	}
	return  id,nil ;
}

// GetWarehous is the resolver for the getWarehous field.
func (r *queryResolver) GetWarehous(ctx context.Context, id string) (*model.Warehouse, error) {
	rsp,err:=r.GetWarehous(ctx,id)
	if err!=nil{
		return nil,err
	}
	return &model.Warehouse{
		ID: rsp.ID,
		Name: rsp.Name,
		City:rsp.City ,
		Address: rsp.Address,
		UpdatedAt: rsp.UpdatedAt,
		CreatedAt: rsp.CreatedAt,
	},nil
}

// GetWarehouses is the resolver for the getWarehouses field.
func (r *queryResolver) GetWarehouses(ctx context.Context) ([]*model.Warehouse, error) {
	rsp,err:=r.GetWarehouses(ctx)
	if err!=nil{
		return  nil,err
	}
	return rsp,nil
}
