syntax = "proto3";
package proto;


option go_package = "./proto/addresspb";


service AddressService{
    rpc GetAddress(GetAddressRequest) returns (GetAddressResponse) ;
}

message GetAddressRequest{
        int64 user_id=1;
		int64 address_id=2;
}


message GetAddressResponse{
        int64 id=1; 
        string full_name=2;
        string phone_number=3;
        string house_no=4;
        string apartment=5;
        string colony=6 ;

        string  city =7;
        string state=8 ;

        int64 user_id=9; 
       string  pin_code=10;
       bool  is_default=11;
}